scatter_ppm works with multi-wavelength fits
kevin218/Eureka pull request #153
Opened 2022-02-28 21:16 UTC by cpiaulet

Make the scatter_ppm parameter robust to having >1 wavelength channel being fitted. Individual scatter_ppm params are created and used for each channel.

2022-02-28 22:49 UTC, taylorbell57 requested changes
I haven't run this, but I think changes similar to the ones you made for emcee need to be made for all the other fitters

2022-02-28 22:49 UTC, taylorbell57 commented on eureka/S5_lightcurve_fitting/fitters.py
> +                lc.unc_fit[chan*lc.time.size:(chan+1)*lc.time.size] = medians[ind[chan]] * 1e-6
Does a similar change to this not also need to be made for the other fitters?

2022-02-28 23:07 UTC, cpiaulet commented
right, I'll get on that :)

2022-03-01 17:44 UTC, cpiaulet commented
@taylorbell57 I just put it in and tested for lsq and dynesty. I also put it in for lmfit but it does not seem to work either way.

2022-03-02 21:54 UTC, taylorbell57 commented
@cpiaulet can you merge the main branch (presumably the remote/main branch for you) into your branch to resolve the merge conflicts and so that I can test out your code?

2022-03-03 01:10 UTC, taylorbell57 approved these changes
Alright, I tried this out in a local branch and it seems to work, so you have my approval. You'll still need to resolve the merge conflicts before you can merge this into main though

2022-03-03 22:11 UTC, cpiaulet commented
done! I had only merged it on the date I opened the pull request :)

2022-03-07 17:07 UTC, taylorbell57 approved these changes

2022-03-08 18:43 UTC, merged