Address issue #193
kevin218/Eureka pull request #254
Opened 2022-04-01 23:31 UTC by AarynnCarter

For certain .ecf parameters it is not possible to perform a background subtraction (see #193) as the median of the error arrays is exactly 0. Adjusting the NIRSpec code to mask these zeroes when calculating the bg_err values. 

This likely only applies for the simulated data, so a warning has been added to the log to remind people when the real data comes around. 

Also removed the manual adjustment from NaN's to 0's as it is no longer needed.

2022-04-02 00:11 UTC, AarynnCarter commented
Just adjusted bright2flux.py to be able to digest the NIRSpec photom crds file. Also added a quick option to convert from MJy to DN/s within the existing `bright2dn()` function using the steradian to pixel conversion in the SCI header. 

This addresses Issue #169 partially, I could probably get NIRISS incorporated next week also.

2022-04-04 23:31 UTC, taylorbell57 requested changes

2022-04-04 23:31 UTC, taylorbell57 commented on eureka/S3_data_reduction/bright2flux.py
>          raise ValueError(f'The bright2dn function has not been edited to handle the instrument {meta.inst}, and can currently only handle miri and nircam observations.')
You can add NIRSpec to the list in this message now

2022-04-04 23:31 UTC, taylorbell57 commented on eureka/S3_data_reduction/s3_reduce.py
> +                log.writelog('WARNING: Are you using real JWST data? Take a look at at the flag_bg() function in nirspec.py and Issue #193 on Github!')
I would instead write:
`log.writelog('WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!')`

2022-04-04 23:32 UTC, taylorbell57 commented
Are there any related issues that can be closed with this PR?

2022-04-05 20:53 UTC, AarynnCarter commented
Okay I incorporated your tweaks @taylorbell57, and I've also added functionality to do the conversion for NIRISS as well.

However, @afeinstein20, @kevin218, I'd appreciate a few more sets of eyes on the NIRISS line, as I'm not entirely sure whether order=1 is the correct choice, or we need to do something more complicated. 

@taylorbell57 this closes #193, and #169, and maybe we could close #99 at the same time. However, I'm not sure how to formally connect these to the pull request beyond including them in the comment text.

2022-04-05 21:00 UTC, taylorbell57 commented
> @taylorbell57 this closes #193, and #169, and maybe we could close #99 at the same time. However, I'm not sure how to formally connect these to the pull request beyond including them in the comment text.

I added them for now, but in the future you can either use the Development section on the right of a PR or use "closing keywords" in your comments (described [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))

2022-04-10 21:12 UTC, kevin218 approved these changes

2022-04-12 22:42 UTC, merged