Decorrelating against x and y position/width
kevin218/Eureka pull request #454
Opened 2022-08-22 14:51 UTC by taylorbell57

This PR has #451 as it's base, so that PR should be merged first.

This PR adds x and y decorrelation to Stage 5 with a new CentroidModel which can be used with four new values accepted by `run_myfuncs` in the Stage 5 ECF: `xpos, ypos, xwidth, ywidth`. This has not been integrated with the photometry edits at this point and is currently only setup to work with spectroscopy. For the `xpos` and `xwidth` to work, you need to use `recordDrift` or `correctDrift` in Stage 4. For the `ypos` and `ywidth` to work , you need to use `record_ypos` in Stage 3 (and need to use `src_pos_type=gaussian` for `ywidth` as that's currently the only method that gives a `ywidth`). Some work will also need to be done to properly handle the WFC3 drift parameters.

This PR also resolves #452 by properly handling the near-zero or below-zero transit depths which had been causing the scale height secondary y-axis to crash. At this point the locations of the scale height tick marks aren't exactly beautifully formatted, but they're functional (they're now evenly spaced to avoid overlapping ticks near Rp=0 which happens if left at their default positions).

This PR also adds LaTeX formatted transmission/emission tables in Stage 6 (working on Issue #188).

This PR also makes sure that `scatter_ppm` and `scatter_mult` both work when they are set to `'fixed'` where they had previously been ignored if set to fixed (sometimes useful for debugging); this resolves #386.

This PR also resolves #439 by adding a second x-axis at the top of the Allan variance plot showing the bin size in units of seconds with the primary x-axis still showing the bin size in number of binned data points.

This PR is still a draft and needs more work on documentation before I set it as ready for review.

2022-08-22 17:11 UTC, taylorbell57 commented
Below is an example of the LaTeX formatted tables made in Stage 6 along with a screenshot of the resulting table once compiled:

```
\begin{deluxetable}{CC|CC|CC|CC}
\tablecaption{\texttt{Eureka!}'s Transit Spectroscopy Results \label{tab:eureka_transit_spectra}}
\tablehead{
\colhead{Wavelength} & \colhead{Transit Depth} &\colhead{Wavelength} & \colhead{Transit Depth} &\colhead{Wavelength} & \colhead{Transit Depth} &\colhead{Wavelength} & \colhead{Transit Depth}  \\
\colhead{($\mu$m)} & \colhead{(ppm)} &\colhead{($\mu$m)} & \colhead{(ppm)} &\colhead{($\mu$m)} & \colhead{(ppm)} &\colhead{($\mu$m)} & \colhead{(ppm)} 
}
\startdata
4.86 & 560^{+85}_{-83}$ & 6.65 & 695^{+56}_{-61}$ & 8.43 & 441^{+54}_{-53}$ & 10.22 & 670^{+75}_{-90}$\\
5.01 & 364^{+75}_{-68}$ & 6.80 & 516^{+47}_{-45}$ & 8.58 & 565^{+66}_{-60}$ & 10.37 & 562^{+89}_{-94}$\\
5.16 & 557^{+80}_{-78}$ & 6.95 & 399^{+56}_{-54}$ & 8.73 & 521^{+61}_{-65}$ & 10.52 & 524^{+101}_{-89}$\\
5.31 & 565^{+83}_{-77}$ & 7.09 & 536^{+45}_{-52}$ & 8.88 & 658^{+57}_{-55}$ & 10.67 & 529^{+97}_{-89}$\\
5.46 & 490^{+85}_{-82}$ & 7.24 & 451^{+52}_{-50}$ & 9.03 & 535^{+61}_{-55}$ & 10.82 & 480^{+120}_{-110}$\\
5.61 & 657^{+60}_{-55}$ & 7.39 & 683^{+49}_{-53}$ & 9.18 & 548^{+64}_{-69}$ & 10.96 & 440^{+110}_{-110}$\\
5.75 & 410^{+64}_{-59}$ & 7.54 & 595^{+52}_{-54}$ & 9.33 & 477^{+63}_{-55}$ & 11.11 & 640^{+130}_{-120}$\\
5.90 & 456^{+49}_{-55}$ & 7.69 & 433^{+49}_{-47}$ & 9.48 & 481^{+69}_{-73}$ & 11.26 & 410^{+120}_{-120}$\\
6.05 & 538^{+54}_{-52}$ & 7.84 & 620^{+53}_{-54}$ & 9.62 & 618^{+65}_{-64}$ & 11.41 & 380^{+120}_{-130}$\\
6.20 & 519^{+55}_{-52}$ & 7.99 & 507^{+50}_{-45}$ & 9.77 & 564^{+71}_{-79}$ & 11.56 & 430^{+140}_{-140}$\\
6.35 & 559^{+54}_{-53}$ & 8.14 & 547^{+51}_{-53}$ & 9.92 & 478^{+72}_{-70}$ & 11.71 & 450^{+160}_{-140}$\\
6.50 & 463^{+47}_{-48}$ & 8.29 & 572^{+56}_{-55}$ & 10.07 & 446^{+70}_{-72}$ & 11.86 & 620^{+170}_{-170}$\\
\enddata
\end{deluxetable}
```

<img width="600" alt="Screen Shot 2022-08-22 at 13 09 57" src="https://user-images.githubusercontent.com/24514122/185979685-4532c44f-0124-469c-a8e4-dbee44644689.png">

2022-08-27 15:09 UTC, kevin218 requested changes

2022-08-27 15:09 UTC, kevin218 commented on src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
> +        centroid_local = self.centroid - self.centroid.mean()
This line doesn't need to be run every time we evaluate the function since the values are static.

2022-08-29 16:45 UTC, taylorbell57 commented on docs/media/S3_template.ecf
> +window_len      31          # Smoothing window length, for median frame or when fittype = smooth or meddata (when computing median frame). Can set to 1 for no smoothing when computing median frame fo
Okay, so do you want me to change all the NIRCam/NIRSpec and documentation ECFs to use 13 then? And should I keep WFC3 as 31 which I assume this default value came from?

2022-08-29 16:46 UTC, taylorbell57 commented on src/eureka/S3_data_reduction/s3_reduce.py
> +        meta.bg_hw_range = [f'{s_in}_{s_out}' for s_in in meta.skyin
Yup, it behaves exactly like ap and bg for spectroscopy. And both have no protections against bg > ap at this point.

2022-08-29 19:38 UTC, taylorbell57 commented on docs/media/S3_template.ecf
> +window_len      31          # Smoothing window length, for median frame or when fittype = smooth or meddata (when computing median frame). Can set to 1 for no smoothing when computing median frame fo
I've now updated NIRCam's ECFs to use 13 and I had already updated the MIRI ECFs to use 1. This particular ECF is for NIRSpec, so I'll update it along with the other NIRSpec values depending on what you want me to do there

2022-08-30 03:47 UTC, kevin218 commented on docs/media/S3_template.ecf
> +window_len      31          # Smoothing window length, for median frame or when fittype = smooth or meddata (when computing median frame). Can set to 1 for no smoothing when computing median frame fo
Let's also go with 13 for NIRSpec. That should at least be closer to the best value.

2022-08-30 03:50 UTC, kevin218 commented on src/eureka/S5_lightcurve_fitting/models/CentroidModel.py
> +        centroid_local = self.centroid - self.centroid.mean()
It'll robably save less time than we've spent pondering how much time it would save... which isn't much.

2022-08-31 00:50 UTC, kevin218 approved these changes

2022-08-31 01:08 UTC, merged