Account for no files in table
kevin218/Eureka pull request #462
Opened 2022-09-01 15:40 UTC by kevin218

mastDownload.py throws an error when there are no files found.

2022-09-01 17:35 UTC, kevin218 commented
@taylorbell57 I decided to take your suggestion and convert the level 4 plot to level 3.

2022-09-01 17:51 UTC, taylorbell57 requested changes

2022-09-01 17:51 UTC, taylorbell57 commented on src/eureka/S3_data_reduction/plots_s3.py
> +    vmax = np.max(2000, vmin + 2000)
You'll need `np.max([2000, vmin+2000])`

2022-09-01 17:56 UTC, taylorbell57 commented
> @taylorbell57 I decided to take your suggestion and convert the level 4 plot to level 3.

You'll need to change the docs pages accordingly

2022-09-09 21:42 UTC, taylorbell57 approved these changes

2022-09-09 21:42 UTC, merged