Add input_meta parameter to every Stage and update write function
kevin218/Eureka pull request #468
Opened 2022-10-06 11:02 UTC by evamariaa

To make it easier to use Eureka! in notebooks and interactively we added a parameter input_meta to every Stage to allow for users to pass meta without loading an .ecf file (See ERS_NIRCam notebook). 

I also added some lines to replace meta.lines in the ecf class if parameters have changed.

2022-10-06 19:43 UTC, taylorbell57 requested changes
Aside from needing to copy-paste the docstring I wrote for Stage 1, this looks good to go!

2022-10-07 09:22 UTC, evamariaa commented on src/eureka/S1_detector_processing/s1_process.py
> +    input_meta : eureka.lib.readECF.MetaClass; optional
Good catch! Done now.

2022-10-07 18:28 UTC, taylorbell57 commented on src/eureka/S1_detector_processing/s1_process.py
> +    input_meta : eureka.lib.readECF.MetaClass; optional
Sorry, I meant the whole docstring, not just this one line. I went ahead and added it myself.

2022-10-07 18:28 UTC, taylorbell57 approved these changes

2022-10-08 06:29 UTC, merged