Enable Binned LC Plots
kevin218/Eureka pull request #512
Opened 2023-03-31 19:48 UTC by kevin218

Working with datasets that have many integrations makes it difficult to see what's going on in the light curve plots.  So, when `meta.nbin_plot` is given, the light curves in all figures are now binned to the desired time resolution.  Before, only some plots were binned.

2023-04-03 18:29 UTC, taylorbell57 requested changes
In addition to the specific feedback below, do we exclusively want to plot the binned data (like I did for Fig5104) or do we want to put the unbinned data in the background using faint, translucent points (like I did for Fig5304) - or do we want to show both using different plots, as I did. I have examples of those two figures below

Fig 5104 example:
![fig5104_ch0_phaseVariations_exoplanet](https://user-images.githubusercontent.com/24514122/229595086-f3f9677c-b4d7-475e-af36-ac52990538e7.png)

Fig 5304 example:
![fig5304_ch0_phaseVariations_exoplanet](https://user-images.githubusercontent.com/24514122/229595120-63951b7a-02fa-4f9b-b35d-f3ef3aa85154.png)

2023-04-03 18:29 UTC, taylorbell57 commented on src/eureka/S5_lightcurve_fitting/plots_s5.py
> +            nbin_plot = len(lc.time)
These should use `time` and not `lc.time` (because `lc.time` can be longer than `time` for multi-white fits).

2023-04-03 18:29 UTC, taylorbell57 commented on src/eureka/S5_lightcurve_fitting/plots_s5.py
> +        binned_time = util.binData(lc.time, nbin_plot)
Again, `time` and not `lc.time` here.

2023-04-03 18:29 UTC, taylorbell57 commented on src/eureka/S5_lightcurve_fitting/lightcurve.py
> +                nbin_plot = len(self.time)
Again, `time` and not `self.time`

2023-04-03 18:29 UTC, taylorbell57 commented on src/eureka/S5_lightcurve_fitting/lightcurve.py
> +            binned_time = util.binData(self.time, nbin_plot)
Again, `time` and not `self.time`

2023-04-04 00:25 UTC, kevin218 commented
I'm going on vacation until April 12th, so you're welcome to make changes to this PR while I'm gone.

I support having Figures 5104 and 5304 as separate plots.

2023-04-04 01:09 UTC, taylorbell57 commented
Can you clarify what you mean by "I support having Figures 5104 and 5304 as separate plots."? To clarify my question, I had meant do we want to:

1. have fig5104 (just binned data) and fig5304 (binned data with unbinned data in the background) equivalents for all the figures you've changed, or
2. just have the fig5014 (just binned data) equivalents that you've made

2023-04-04 01:23 UTC, kevin218 commented
Ok, now I see what you're asking.

For the 3 panel plot (raw, normalized, residuals), I would prefer using only the binned data so that the default ylim range gives meaningful information.

I'm ok with plotting both for the single-panel light curve.

2023-04-04 01:27 UTC, taylorbell57 commented
Okay, I'll try to make both for the single-panel lightcurve if I find the time before you get back.

2023-04-06 23:33 UTC, taylorbell57 approved these changes

2023-04-07 00:12 UTC, merged