Stage 4cal (Calibrated Stellar Spectra)
kevin218/Eureka pull request #728
Opened 2024-12-16 23:12 UTC by kevin218

**This PR is not quite ready for review**

2025-01-08 04:59 UTC, taylorbell57 requested changes
I haven't made it through all the files yet (and haven't looked at most of your new code yet), but here are some preliminary comments

2025-01-08 04:59 UTC, taylorbell57 commented on docs/source/stages.rst
> +- **Stage 4cal:** Using Stage 3 calibrated-flux outputs, generates median calibrated stellar spectra using in-eclipse data and out-of-eclipse baseline.  The outputs also include the standard deviatio
Do you really mean "in-eclipse data and out-of-eclipse baseline" - I assume that's supposed to be "in-eclipse data and out-of-transit baseline"

2025-01-08 04:59 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
Why was this file deleted?

2025-01-08 04:59 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage2/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_calints.fits
Why was this file deleted?

2025-01-08 04:59 UTC, taylorbell57 commented on tests/test_NIRSpec.py
> +# Last Updated: 2024-12-30
I think we should just remove these lines

2025-01-08 04:59 UTC, taylorbell57 commented on tests/test_NIRSpec.py
> -    pass
We had these old lines (and the related `s2_installed` code) since S2 will fail to import if `jwst` is not installed, and we hadn't wanted to make that a mandatory installation requirement.

2025-01-08 20:37 UTC, kevin218 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
The file was replaced with real NIRSpec data that works for the calibrated stellar spectrum pipeline.

2025-01-08 20:38 UTC, kevin218 commented on tests/data/JWST-Sim/NIRSpec/Stage2/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_calints.fits
This file is no longer needed since tests now start from Stage 1 outputs.

2025-01-08 20:43 UTC, kevin218 commented on tests/test_NIRSpec.py
> -    pass
I don't see any reason why someone would want to test just the NIRSpec pipeline without having `jwst` installed.  At this point, I think you and I (and GitHub) are the only ones running these tests.

2025-01-08 21:03 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
The new file isn't on GitHub - you'll need to force add the new file since .fits files are ignored by default

2025-01-08 22:59 UTC, kevin218 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
I already added it directly to GitHub via the browser. It was too large for a PR

2025-01-09 01:24 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
Ah, gotcha - I see it

2025-01-09 01:24 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
Actually, you should merge the main branch into this branch so that file gets copied over here

2025-01-09 01:27 UTC, taylorbell57 commented on tests/data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits
Scratch that, it appears you already have

2025-01-10 15:30 UTC, sebastian-zieba commented
Hi, I'm currently testing this PR on some MIRI/LRS data and it works great!
Just wanted to say that I guess the `run_eureka.py` file should be updated too with something like 
`meta, spec, ds = s4cal.medianCalSpec(eventlabel, ecf_path=ecf_path)`

2025-01-16 22:23 UTC, kevin218 commented
> Hi, I'm currently testing this PR on some MIRI/LRS data and it works great! Just wanted to say that I guess the `run_eureka.py` file should be updated too with something like `meta, spec, ds = s4cal.medianCalSpec(eventlabel, ecf_path=ecf_path)`

I'm glad it's working out and thanks for the suggestion!  I've added a suitable `run_eureka.py` file to the S4cal demos folder.

2025-02-03 21:23 UTC, taylorbell57 requested changes

2025-02-03 21:23 UTC, taylorbell57 commented on demos/JWST/CalibratedStellarSpectra/S2_nirspec_fs_template.ecf
> +# Eureka! Control File for Stage 2: Data Reduction
Do we want to have calibrated spectra demo files for all the other instruments as well?

2025-02-03 21:23 UTC, taylorbell57 commented on demos/JWST/CalibratedStellarSpectra/S4cal_template.ecf
> +# Eureka! Control File for Stage 4cal: Calibrated Stellar Spectra
See the comments I left on the `docs/media/S4cal_template.ecf` file

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_meta.py
> +        # self.testing_S4cal = getattr(self, 'testing_S4cal', False)
Remove commented-out line if not needed

2025-02-03 21:23 UTC, taylorbell57 commented on docs/media/S4cal_template.ecf
> +# t23             0.00            # Full transit duration
Having these set to 0 in the template looks dangerous to me - they only get updated if they're set to `None`. I know these lines are commented out, but still seems safer to either set these to some arbitrary values (like those for WASP-39b or whatever system you've used for the other settings) or set them to `None`

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_meta.py
> +        self.t23 = getattr(self, 't23', None)
Either need to update templates to show example values of `None` or replace any `0.0` values with `None`s here.

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +from eureka.S4cal_StellarSpectra.s4cal_meta import S4cal_MetaClass
This style of importing eureka components isn't consistent with what we've done everywhere else, and I think in theory it could cause headaches when using Eureka!'s code without installing it (which I often do when testing/tweaking things).

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +                                 name='Std. Dev. of In-Eclipse Flux')
Much of this code should be broken out into smaller, task-specific functions to maintain modularity and ease of code review

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +        # Indeces for first through fourth contact
indices

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +        # Indeces for first through fourth contact
Same for below

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +        igood = np.where(~mask)[0]
Should any of the wavelength-axis masking parameters be user-controllable?

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +def plot_whitelc(optspec, time, meta, i, fig=None, ax=None):
Do we want to keep these plotting functions in the same file, or move them out to a separate plots_s4cal.py file like we've done with other stages?

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +    '''
Please add full docstring

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +    '''
Please add full docstring

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +    return fig, ax
Add code to pop up the figures like we have for other stages.

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +    return
Add code to pop up the figures like we have for other stages.

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +                bbox_inches='tight', dpi=300)
In the case of multiple inputted eclipses/transits (which seems to be supported given the `for i in range(num_ecl):` line in the function above), this plot will be overwritten for each transit/eclipse. Need to have something in the filename distinguishing which transit/eclipse number.

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +              ymin, ymax, color=colors[0], label='In-Eclipse Region')
Would "In-Occultation" be better, given that this may be applied to transit data as well?

2025-02-03 21:23 UTC, taylorbell57 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +                    fmt='.', ms=1, label=f'In-Eclipse ({ds.time.values[i]})',
Would "In-Occultation" be better, given that this may be applied to transit data as well?

2025-02-04 23:43 UTC, kevin218 commented on docs/source/ecf.rst
> +Optional.  Full transit duration, from t2 to t3.  The data points between t2 and t3 are used to determine the in-transit flux.  When not given, t23 is computed using the orbital parameters above.  Wh
![transit_shape2](https://github.com/user-attachments/assets/18987f96-f449-46f8-9ec9-012f1c9efa24)
Does this work?

2025-02-04 23:44 UTC, kevin218 commented on demos/JWST/CalibratedStellarSpectra/S2_nirspec_fs_template.ecf
> +# Eureka! Control File for Stage 2: Data Reduction
This is a good long-term goal.  I'll see what I have on hand, but it won't be complete.

2025-02-04 23:51 UTC, kevin218 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +from eureka.S4cal_StellarSpectra.s4cal_meta import S4cal_MetaClass
Good catch!  I do the same.

2025-02-05 14:37 UTC, taylorbell57 commented on docs/source/ecf.rst
> +Optional.  Full transit duration, from t2 to t3.  The data points between t2 and t3 are used to determine the in-transit flux.  When not given, t23 is computed using the orbital parameters above.  Wh
Yeah, that'd work nicely

2025-02-11 20:53 UTC, kevin218 commented on src/eureka/S4cal_StellarSpectra/s4cal_StellarSpec.py
> +                bbox_inches='tight', dpi=300)
The code works as intended.  In the case of multiple occultations, this is what you get.  As you can see, there's no benefit to plotting the marked regions for just one of the occultations.
![Figure_4202](https://github.com/user-attachments/assets/055acc3b-64e6-4494-80dc-35387128ead9)

2025-02-12 18:01 UTC, taylorbell57 requested changes

2025-02-12 18:23 UTC, taylorbell57 commented
Also, please look into the installation issues raised by the PyMC3 test

2025-02-12 19:03 UTC, kevin218 commented
> Also, please look into the installation issues raised by the PyMC3 test

The issue is a conflict between jwst and pastasoss:
`jwst 1.11.4 depends on scipy<1.10.0 and >=1.6.0`
`pastasoss 1.2.1 depends on scipy>=1.10.1`
I have an issue in with [pastasoss](https://github.com/spacetelescope/pastasoss/issues/13), but there's been no movement.

2025-02-12 20:14 UTC, taylorbell57 approved these changes

2025-02-12 20:21 UTC, merged