Adding optimal photometric extraction and photutils aperture extraction
kevin218/Eureka pull request #729
Opened 2024-12-18 08:10 UTC by taylorbell57

This PR resolves #491, resolves #514, and makes a lot of progress on #495.

This PR adds:

1. error-weighted optimal photometric extraction using a somewhat similar method to our spectroscopy code. I currently do not have code to mask pixels that deviate too far from the spatial profile; let me know if you think that's critical to add at this stage.

2. aperture photometric extraction using the open-source photutils, which allows for different aperture shapes, different aperture edges (allowing for "center" edges where a pixel is either inside the aperture or outside the aperture depending on whether the center of the pixel lies within the aperture, or "exact" edges where each pixel is weighted by the fractional area of the pixel that lies within the aperture), and is a fast and performant package.

This PR also greatly speeds up:

1. the flagging of bad pixels in photometry data by re-using the `nircam.flag_ff` function

2. the interpolation-based replacement of bad pixels for photometric data by adding multiprocessing support

I also restructured the photometry code to run each step for all integrations before moving on to the next step. This makes parallelizing easier and makes some steps easier.

I also fixed a bug with meanerr which was causing np.nan values to be returned for skyerr. There were also a couple other bug patches throughout.

Things remaining to do before the PR is ready for review:

- [ ] Tidy up the apphot.apphot function inputs and outputs to be more like apphot.photutils_apphot
- [ ] Add support for `aperture_edge='exact'` when `phot_method='optimal'`
- [ ] Manually test `phot_method='poet'` and check that it is as good or better than before
- [ ] Manually test `phot_method='photutils'` and check that it performs at least similar to poet
- [ ] Manually test `phot_method='optimal'` and check that it performs at least similar to poet
- [ ] Add documentation for new S3 meta parameters
- [ ] Make sure all new functions have proper docstrings

2024-12-19 05:57 UTC, taylorbell57 commented
@kevin218, I still need to fix figs 3306 and 3504 to show the new aperture shapes, but otherwise this PR is ready for review. Tomorrow is my last work day before the holidays, so I likely won't get to fixing those figures until the new year

2025-02-17 19:48 UTC, kevin218 requested changes

2025-02-17 19:48 UTC, kevin218 commented on src/eureka/lib/util.py
> +    # x,y positions of not masked pixels
Same here

2025-02-17 19:48 UTC, kevin218 commented on src/eureka/lib/apphot.py
>          apFunc = di.disk
If we haven't done so already, we should catch the case where the aperture shape isn't hexagon or circle.

2025-02-17 19:48 UTC, kevin218 commented on src/eureka/lib/apphot.py
>      # FINDME: include NaNs and zero errors
Do we still need this FINDME?

2025-02-17 19:48 UTC, kevin218 commented on src/eureka/lib/apphot.py
Take a look at the duplicate code in both the `optphot` and `photutils_apphot` routines and see if it's worth breaking out into smaller functions.  It may not be, but it's worth a look.

2025-02-20 16:53 UTC, taylorbell57 commented on src/eureka/lib/apphot.py
>          apFunc = di.disk
This has already been caught in s3_meta.py

2025-02-20 17:11 UTC, taylorbell57 commented on src/eureka/S3_data_reduction/s3_reduce.py
> +                            data.flux.attrs['flux_units']
That function was a bit more specialized than I'd wanted to use, but I made some tweaks to now be able to reuse that function

2025-02-20 17:43 UTC, taylorbell57 commented on src/eureka/lib/apphot.py
>      # FINDME: include NaNs and zero errors
We were already counting NaNs, but not zero errors, so I added that above and have now removed this FINDME

2025-02-20 20:07 UTC, taylorbell57 commented
From my testing on TRAPPIST-1 photometry observations, this PR resolves #745

2025-02-28 22:57 UTC, kevin218 commented on src/eureka/lib/apphot.py
Ok!

2025-03-03 16:59 UTC, kevin218 requested changes

2025-03-03 16:59 UTC, kevin218 commented on src/eureka/S3_data_reduction/plots_s3.py
> +    # Plot proper aperture shapes
Needs documentation

2025-03-06 20:56 UTC, kevin218 approved these changes

2025-03-06 21:29 UTC, merged